# Generated by Django 4.1.2 on 2023-01-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0002_remove_cliente_id_cliente_direccion_cliente_movil_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('nombre', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('lugar', models.CharField(max_length=150, null=True)),
                ('precio', models.CharField(max_length=14, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
