# Generated by Django 4.1.2 on 2023-01-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0003_concierto_alter_cliente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='nombre',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
