# Generated by Django 4.1.2 on 2023-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0004_alter_concierto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='fecha',
            field=models.DateField(),
        ),
    ]
