# Generated by Django 4.1.2 on 2023-01-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0005_alter_concierto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='lugar',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='concierto',
            name='precio',
            field=models.CharField(max_length=14),
        ),
    ]
