# Generated by Django 4.1.2 on 2023-01-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0006_alter_concierto_lugar_alter_concierto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
