# Generated by Django 4.1.2 on 2023-02-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0007_alter_concierto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='concierto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='misitio', verbose_name='Imagen'),
        ),
    ]
