# Generated by Django 4.1.2 on 2023-02-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0008_concierto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concierto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imgConciertos', verbose_name='Imagen'),
        ),
    ]
